# Generated by Django 5.0.1 on 2024-01-31 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=250, null=True)),
                ('prenom', models.CharField(blank=True, max_length=250, null=True)),
                ('numero_permis_conduire', models.CharField(max_length=20, unique=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('disponibilite', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=250)),
                ('permis', models.CharField(max_length=250)),
                ('num_cni', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images/')),
            ],
        ),
        migrations.CreateModel(
            name='Deplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateTimeField(blank=True, null=True)),
                ('date_arrivee', models.DateTimeField(blank=True, null=True)),
                ('lieu_depart', models.CharField(max_length=250)),
                ('niveau_carburant', models.IntegerField()),
                ('lieu_arrivee', models.CharField(max_length=250)),
                ('duree_deplacement', models.CharField(max_length=250)),
                ('depart', models.BooleanField(default=False)),
                ('arrivee', models.BooleanField(default=False)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('kilometrage_depart', models.IntegerField()),
                ('statut', models.CharField(choices=[('en attente de départ', 'en attente de départ'), ('en cours', 'En cours...'), ('arrivée', 'Arrivée')], default='en attente de départ', max_length=50)),
                ('conducteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.conducteur')),
            ],
        ),
        migrations.CreateModel(
            name='EtatArrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometrage_arrive', models.IntegerField()),
                ('niveau_carburant_a', models.IntegerField()),
                ('date_arrive', models.DateField()),
                ('deplacement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.deplacement')),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.photo')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_immatriculation', models.CharField(max_length=250)),
                ('couleur', models.CharField(max_length=250)),
                ('carte_grise', models.CharField(max_length=250)),
                ('date_mise_circulation', models.DateField()),
                ('date_d_edition', models.DateField()),
                ('type_commercial', models.CharField(max_length=250)),
                ('carrosserie', models.CharField(max_length=250)),
                ('energie', models.CharField(max_length=250)),
                ('place_assises', models.IntegerField()),
                ('date_expiration_assurance', models.DateField()),
                ('date_videnge', models.DateField()),
                ('kilometrage', models.IntegerField()),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.photo')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.marque')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_incident', models.TextField()),
                ('conducteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.conducteur')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.photo')),
                ('vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entretien', models.DateField(blank=True, null=True)),
                ('prix_entretient', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.vehicule')),
            ],
        ),
        migrations.AddField(
            model_name='deplacement',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.vehicule'),
        ),
    ]
