# Generated by Django 5.0.1 on 2024-02-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etatarrive',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='image',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='image',
            field=models.ManyToManyField(related_name='vehicule_images', to='Model.photo'),
        ),
    ]
