# Generated by Django 4.2.7 on 2024-01-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conducteur',
            name='disponibilite',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='disponibilite',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Deplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateTimeField(blank=True, null=True)),
                ('date_arrivee', models.DateTimeField(blank=True, null=True)),
                ('lieu_depart', models.CharField(max_length=250)),
                ('lieu_arrivee', models.CharField(max_length=250)),
                ('details', models.TextField(blank=True, null=True)),
                ('depart', models.BooleanField(default=False)),
                ('arrivee', models.BooleanField(default=False)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('conducteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.conducteur')),
                ('vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.vehicule')),
            ],
        ),
    ]
