# Generated by Django 5.0.1 on 2024-02-01 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_remove_etatarrive_photo_remove_incident_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Model.vehicule'),
        ),
    ]
