# Generated by Django 5.0.1 on 2024-01-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0003_deplacement_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicule_images/'),
        ),
        migrations.AlterField(
            model_name='deplacement',
            name='statut',
            field=models.CharField(choices=[('en attente de départ', 'en attente de départ'), ('en cours', 'En cours...'), ('arrivée', 'Arrivée')], default='en attente de départ', max_length=50),
        ),
    ]
